name: bigaze
description: AI Powered proctoring 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_launcher: ^2.0.7
  animated_splash_screen: ^1.3.0
  animated_bottom_navigation_bar: ^1.3.3
  glassmorphism: ^3.0.0
  permission_handler: ^11.3.1
  tflite_flutter: ^0.10.4
  camera: ^0.10.3+2
  flutter_tflite: ^1.0.1
  glowy_borders: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  simple_animated_button: ^0.0.9
  glass_kit: ^3.0.0
  uuid: ^4.3.3
  provider: ^6.1.2
  fl_chart: ^0.67.0
  pdf: ^3.8.4
  printing: ^5.9.3
  image_picker: ^0.8.9
  syncfusion_flutter_pdf: ^25.1.38
  photo_view: ^0.14.0
  path_provider: ^2.1.2
  flutter_share: ^2.0.0
  wakelock: ^0.6.2
  internet_speed_meter: ^1.0.2
  dart_ping: ^9.0.1
  giffy_dialog: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/AppIcons/android/mipmap-xhdpi/bigaze.png
    - assets/images/AppIcons/android/mipmap-xxhdpi/bigaze.png
    - assets/images/AppIcons/android/mipmap-xxxhdpi/bigaze.png
    - assets/models/
    - assets/models/mobilenet_v1_1.0_224.tflite
    - assets/models/mobilenet_v1_1.0_224.txt
    - assets/models/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/models/yolov2_tiny.txt
    - assets/models/yolov2_tiny.tflite
    - assets/models/yamnet.tflite
    - assets/models/yamnet_label_list.txt
    - assets/models/ssd_mobilenet.txt
    - assets/models/ssd_mobilenet.tflite
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

icons_launcher:
  image_path: "assets/images/AppIcons/android/mipmap-xxxhdpi/bigaze.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/AppIcons/android/mipmap-xxxhdpi/bigaze.png"
      adaptive_background_color: '#000000'
      adaptive_foreground_image: 'assets/images/AppIcons/android/mipmap-xxxhdpi/bigaze.png'